In [83]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [84]:
ad_df = pd.read_csv('adsdata_1.csv', index_col=0)
ad_df.dtypes

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


0        object
1        object
2        object
3        object
4       float64
         ...   
1554    float64
1555    float64
1556    float64
1557    float64
1558     object
Length: 1559, dtype: object

In [85]:
ad_df.head(15)

0     1       2  3    4    5    6    7    8    9  ...  1549  1550  \
0.0    125   125       1  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1.0     57   468  8.2105  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2.0     33   230  6.9696  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3.0     60   468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4.0     60   468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
5.0     60   468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
6.0     59   460  7.7966  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
7.0     60   234     3.9  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
8.0     60   468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9.0     60   468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
10.0     ?     ?       ?  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
11.0    90    52  0.5777  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
12.0    90    60  0.6666  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
13.0    90    60  0.6666  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
14.0    33   230  6.9696  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

      1551  1552  1553  1554  1555  1556  1557  1558  
0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
1.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
2.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
3.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
4.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
5.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
6.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
7.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
8.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
9.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
10.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
11.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
12.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
13.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
14.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  

[15 rows x 1559 columns]

some fields contain invalid data, which has to be removed before we train our model

In [86]:
ad_df2 = ad_df.applymap(lambda val: np.nan if str(val).strip() == '?' else val)
ad_df2 = ad_df2.dropna()
ad_df2.head(15)

0    1       2  3    4    5    6    7    8    9  ...  1549  1550  \
0.0   125  125       1  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1.0    57  468  8.2105  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2.0    33  230  6.9696  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3.0    60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4.0    60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
5.0    60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
6.0    59  460  7.7966  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
7.0    60  234     3.9  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
8.0    60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9.0    60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
11.0   90   52  0.5777  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
12.0   90   60  0.6666  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
13.0   90   60  0.6666  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
14.0   33  230  6.9696  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
15.0   60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

      1551  1552  1553  1554  1555  1556  1557  1558  
0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
1.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
2.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
3.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
4.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
5.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
6.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
7.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
8.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
9.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
11.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
12.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
13.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
14.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   ad.  
15.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   ad.  

[15 rows x 1559 columns]

We will now use the label encorder to convert the y values to numeric

In [87]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(ad_df2.iloc[:, -1])

In [88]:
y[0:5]

array([0, 0, 0, 0, 0])

In [89]:
X = ad_df2.iloc[:,:-1]

In [90]:
X.head(5)

0    1       2  3    4    5    6    7    8    9  ...  1548  1549  1550  \
0.0  125  125       1  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
1.0   57  468  8.2105  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
2.0   33  230  6.9696  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
3.0   60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
4.0   60  468     7.8  1  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   

     1551  1552  1553  1554  1555  1556  1557  
0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1558 columns]

Using standard scaler we will now normalize the X values

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [92]:
X[0:5,:]

array([[ 1.11332804, -0.23524739, -0.48180809, ..., -0.12272017,
        -0.09922646, -0.02912965],
       [-0.12597621,  2.39895364,  0.71081076, ..., -0.12272017,
        -0.09922646, -0.02912965],
       [-0.5633777 ,  0.57114068,  0.50556553, ..., -0.12272017,
        -0.09922646, -0.02912965],
       [-0.07130102,  2.39895364,  0.64291394, ..., -0.12272017,
        -0.09922646, -0.02912965],
       [-0.07130102,  2.39895364,  0.64291394, ..., -0.12272017,
        -0.09922646, -0.02912965]])

Now we will split the data into two sets

In [99]:
from sklearn.model_selection import train_test_split


split_size=0.3

#Creation of Train and Test dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=split_size,random_state=22)

#Creation of Train and validation dataset
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train,test_size=0.2,random_state=5)

In [100]:
print ("Train dataset: {0}{1}".format(X_train.shape, y_train.shape))
print ("Validation dataset: {0}{1}".format(X_val.shape, y_val.shape))
print ("Test dataset: {0}{1}".format(X_test.shape, y_test.shape))

Train dataset: (1320, 1558)(1320,)
Validation dataset: (331, 1558)(331,)
Test dataset: (708, 1558)(708,)


In [101]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [102]:
models = []
names = ['Random Forest','Neural Network','GaussianNB','DecisionTreeClassifier','SVM',]

models.append((RandomForestClassifier(n_estimators=100)))
models.append((MLPClassifier()))
models.append((GaussianNB()))
models.append((DecisionTreeClassifier()))
models.append((SVC()))

In [103]:
print (models)

[RandomForestClassifier(), MLPClassifier(), GaussianNB(), DecisionTreeClassifier(), SVC()]


In [104]:
from sklearn import model_selection
from sklearn.metrics import accuracy_score

In [105]:
kfold = model_selection.KFold(n_splits=5,random_state=None)

for i in range(0,len(models)):    
    cv_result = model_selection.cross_val_score(models[i],X_train,y_train,cv=kfold,scoring='accuracy')
    score=models[i].fit(X_train,y_train)
    prediction = models[i].predict(X_val)
    acc_score = accuracy_score(y_val,prediction)     
    print ('-'*40)
    print ('{0}: {1}'.format(names[i],acc_score))
    

----------------------------------------
Random Forest: 0.9848942598187311
----------------------------------------
Neural Network: 0.9758308157099698
----------------------------------------
GaussianNB: 0.7885196374622356
----------------------------------------
DecisionTreeClassifier: 0.9848942598187311
----------------------------------------
SVM: 0.9425981873111783


In [106]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [107]:
randomForest = RandomForestClassifier(n_estimators=100)
randomForest.fit(X_train,y_train)
prediction = randomForest.predict(X_test)

In [108]:
print ('-'*40)
print ('Accuracy score:')
print (accuracy_score(y_test,prediction))
print ('-'*40)
print ('Confusion Matrix:')
print (confusion_matrix(y_test,prediction))
print ('-'*40)
print ('Classification Matrix:')
print (classification_report(y_test,prediction))

----------------------------------------
Accuracy score:
0.9675141242937854
----------------------------------------
Confusion Matrix:
[[ 95  17]
 [  6 590]]
----------------------------------------
Classification Matrix:
              precision    recall  f1-score   support

           0       0.94      0.85      0.89       112
           1       0.97      0.99      0.98       596

    accuracy                           0.97       708
   macro avg       0.96      0.92      0.94       708
weighted avg       0.97      0.97      0.97       708

